apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/serhern831/cis-92:milestone-5.3
    ports:
    - containerPort: 80
    env:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: key
          key: SECRET_KEY
    - name: PORT
      value: "80"
    - name: DB_NAME
      value: "mysite"
    - name: DB_USER
      value: "postgres"
    - name: DB_PASSWORD
      value: "django"
    - name: DB_HOST
      value: "postgres"
    #livenessProbe:
      #httpGet:
        #path: /polls/
        #port: 80
    resources:
      requests:
        cpu: 250m
        memory: 128Mi
      limits:
        cpu: 1000m
        memory: 1Gi